name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: now it is
        run: |
          date
      - name: directory content
        run: ls -l

  check_commit_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        id: check_commit
        run: echo "Commit message: ${{ github.event.head_commit.message }}"
        
      - name: Skip deployment
        if: contains(steps.check_commit.outputs.check_commit, 'skip')
        run: echo "Deployment skipped due to commit message"
        
      - name: Deploy
        if: steps.check_commit.outputs.check_commit != 'skip'
        run: echo "Deploying..."
