on:
  push:
    branches:
      - main
jobs:
   main:
    name: Deploy to Render
    runs-on: ubuntu-latest
            
    steps:
      - name: Render Deployment
        run: https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}